### ISSUE TITLE
关于ElementUI的样式覆盖问题

### ISSUE THREAD

**Issue by ohhoney1** [Stevenzwzhai/vue2.0-elementUI-axios-vueRouter#1]
你好。请教一个问题，关于ElementUI的样式覆盖问题。有一些基础样式，比如input，某些样式很难做到覆盖，在style标签里，我去点scoped的才可以，这样又会有额外的问题，每个组件需要的样式不一样，请问有什么经验可以分享吗（现在，一些公共的样式并且叠加不了的，我会放到父组件中，当然，父组件的style标签去掉了scoped）

**Comment by Stevenzwzhai** [comment]
一般自己定义class，某些无法覆盖的使用important或者直接找到该属性源码class重写

**Comment by ohhoney1** [comment]
在项目中使用有段时间了，我现在的做法是 多加一个style标签，不加scoped，（尤雨溪大大也讲过，这样一个vue文件两个<style></style>）这个负责难覆盖的样式。
还是尽量不用！important，感觉改源码也不太好

**Comment by Stevenzwzhai** [comment]
这样啊，我这里处理的不多，所以也没怎么研究过，受教了

**Comment by andyComeOn** [comment]
你好，在博客园看到你说的可以单独引入`<script src="https://unpkg.com/axios/dist/axios.min.js"></script>`，我的是单页面应用（就是写的一个html文件，通过引入vue.js、axios.min.js实现一些小的逻辑），这种怎么实现数据的抓取、setData()的呢？

**Comment by ohhoney1** [comment]
@andyComeOn 你可以参照一下这个模板，我觉得不错。[https://github.com/taylorchen709/vueAdmin](url)

**Comment by andyComeOn** [comment]
@ohhoney1  好的，多谢你。

**Comment by Stevenzwzhai** [comment]
这个跟你使用vue差不多啊，只不过是没办法使用import和export.

**Comment by qiqi-tian-xia-di-y-ike-ai** [comment]
关于这个问题，我之前用 >>> 或者 /deep/ 是可以对element的组件样式覆盖，但是有一些项目就是不行。我也试过给组件定义了class选择器，或者直接在标签添加:style="{ 'background-color': 'rgba(255, 255, 255, 0.5)' }"这样之类的。结果是都没任何效果。
